/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package banking.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abrar
 */
public class MakeAccount extends javax.swing.JFrame {

    /**
     * Creates new form MakeAccount
     */
    // account making method
    public MakeAccount() {
        initComponents();
       // setLocation(300,100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameTxt = new javax.swing.JTextField();
        MotherTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        AdrsTxt = new javax.swing.JTextField();
        BtnApply = new javax.swing.JButton();
        lMessage = new javax.swing.JLabel();
        BtnBack = new javax.swing.JButton();
        GenderCombo = new javax.swing.JComboBox();
        DateTxt = new javax.swing.JTextField();
        FatherTxt = new javax.swing.JTextField();
        MaritalCombo = new javax.swing.JComboBox();
        ContactTxt = new javax.swing.JTextField();
        AmountTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NIDTxt = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 195, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Father's Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 253, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mother's Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 307, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Gender");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 196, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 248, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Marital Status");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 417, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Date of Birth");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 361, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(752, 296, -1, -1));

        NameTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 193, 301, 31));

        MotherTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(MotherTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 306, 301, 29));

        EmailTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(EmailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 246, 298, 31));

        AdrsTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AdrsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdrsTxtActionPerformed(evt);
            }
        });
        getContentPane().add(AdrsTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 295, 301, 29));

        BtnApply.setBackground(new java.awt.Color(255, 153, 51));
        BtnApply.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BtnApply.setText("Done");
        BtnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnApplyActionPerformed(evt);
            }
        });
        getContentPane().add(BtnApply, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 580, 90, 40));

        lMessage.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lMessage.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(lMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(711, 779, 261, 25));

        BtnBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnBack.setText("Back");
        BtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBackActionPerformed(evt);
            }
        });
        getContentPane().add(BtnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 583, 70, 50));

        GenderCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        GenderCombo.setForeground(new java.awt.Color(0, 153, 153));
        GenderCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        GenderCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderComboActionPerformed(evt);
            }
        });
        getContentPane().add(GenderCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(827, 193, 298, 29));

        DateTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(DateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 360, 301, 29));

        FatherTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(FatherTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 252, 301, 29));

        MaritalCombo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MaritalCombo.setForeground(new java.awt.Color(0, 153, 153));
        MaritalCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Married", "Unmarried" }));
        MaritalCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaritalComboActionPerformed(evt);
            }
        });
        getContentPane().add(MaritalCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 414, 302, 29));

        ContactTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ContactTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactTxtActionPerformed(evt);
            }
        });
        getContentPane().add(ContactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 347, 301, 31));

        AmountTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AmountTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmountTxtActionPerformed(evt);
            }
        });
        getContentPane().add(AmountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 468, 301, 31));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Contact No.");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(719, 349, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("NID No.");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(748, 416, -1, -1));

        NIDTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        NIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NIDTxtActionPerformed(evt);
            }
        });
        getContentPane().add(NIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(826, 407, 301, 31));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, -1, -1));

        jPanel2.setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking/management/system/Άνοιγμα Ελληνικών και Ευρωπαϊκών τραπεζικών λογαριασμών 1.jpg"))); // NOI18N
        jPanel2.add(jLabel13);
        jLabel13.setBounds(0, 90, 1150, 790);

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 60)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Open an account");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 450, 70));

        jPanel2.add(jPanel1);
        jPanel1.setBounds(0, 0, 1151, 92);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 1150, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTxtActionPerformed
// Users detail input 
    private void BtnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnApplyActionPerformed
        // TODO add your handling code here:
        lMessage.setText("");
        
        if(NameTxt.getText().trim().equals("")
           ||FatherTxt.getText().trim().equals("")
           ||MotherTxt.getText().trim().equals("")  
           ||DateTxt.getText().trim().equals("")   
           ||MaritalCombo.getSelectedItem().toString().trim().equals("")
           ||GenderCombo.getSelectedItem().toString().trim().equals("")
           ||EmailTxt.getText().trim().equals("")
           ||AdrsTxt.getText().trim().equals("")
           ||ContactTxt.getText().trim().equals("")
           ||NIDTxt.getText().trim().equals("")
           ||AmountTxt.getText().trim().equals(""))
            //If any information left 
          {
            lMessage.setText("You should not blank any information");
          }
        else
        {
            
        String query;
        ///value initialization 
        
        query = "insert into Account (Name,Father,Mother,Dates,Marital,Gender,Email,Addres,Contact,NID,Amount)"
                + " values ("+"'"+NameTxt.getText()+"',"+
                "'"+FatherTxt.getText()+"',"+"'"+MotherTxt.getText()+"',"+
                "'"+DateTxt.getText()+"',"+"'"+MaritalCombo.getSelectedItem().toString()+"',"+
                "'"+GenderCombo.getSelectedItem().toString()+"',"+
                "'"+ EmailTxt.getText()+"',"+"'"+AdrsTxt.getText()+"',"+"'"+ContactTxt.getText()+"',"+
                "'"+NIDTxt.getText()+"',"+"'"+AmountTxt.getText()+"')";
                
        System.out.println(query);
        
        try {  
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Bank;user=sa;password=sys123";
        
            Connection con = DriverManager.getConnection(connectionUrl);
        
            Statement st=con.createStatement();
            st.execute(query);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MakeAccount.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MakeAccount.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }
        
        
        //new Create_Pass().setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_BtnApplyActionPerformed

    private void BtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBackActionPerformed
        // TODO add your handling code here:
        new Admin1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BtnBackActionPerformed
// all information combo box
    private void AdrsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdrsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdrsTxtActionPerformed

    private void GenderComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderComboActionPerformed

    private void MaritalComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaritalComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaritalComboActionPerformed

    private void ContactTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactTxtActionPerformed

    private void AmountTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmountTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AmountTxtActionPerformed

    private void NIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NIDTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakeAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakeAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdrsTxt;
    private javax.swing.JTextField AmountTxt;
    private javax.swing.JButton BtnApply;
    private javax.swing.JButton BtnBack;
    private javax.swing.JTextField ContactTxt;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JTextField FatherTxt;
    private javax.swing.JComboBox GenderCombo;
    private javax.swing.JComboBox MaritalCombo;
    private javax.swing.JTextField MotherTxt;
    private javax.swing.JTextField NIDTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lMessage;
    // End of variables declaration//GEN-END:variables
}
