/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package banking.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abrar
 */
public class Transaction extends javax.swing.JFrame {

    /**
     * Creates new form BookIssue
     */
    public Transaction() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        FindBtn = new javax.swing.JButton();
        LabelMessage = new javax.swing.JLabel();
        NewAmntTxt = new javax.swing.JTextField();
        PreAmntTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CreditBtn = new javax.swing.JButton();
        DebitBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ClientList = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        IDTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDTxtMouseClicked(evt);
            }
        });
        getContentPane().add(IDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 110, 275, 37));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Account No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 114, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Previous Amount");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 161, -1, -1));

        jLabel1.setBackground(new java.awt.Color(204, 153, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 51));
        jLabel1.setText("    Transaction");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 9, 250, -1));

        FindBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FindBtn.setForeground(new java.awt.Color(0, 153, 153));
        FindBtn.setText("Find");
        FindBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindBtnActionPerformed(evt);
            }
        });
        getContentPane().add(FindBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(802, 122, 69, -1));

        LabelMessage.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelMessage.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(LabelMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(876, 86, 298, 29));

        NewAmntTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(NewAmntTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 207, 275, 33));

        PreAmntTxt.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(PreAmntTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 158, 275, 34));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("New Amount");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 207, -1, -1));

        CreditBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        CreditBtn.setText("Credit");
        CreditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CreditBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 275, -1, -1));

        DebitBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        DebitBtn.setText("Debit");
        DebitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DebitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(DebitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(638, 275, -1, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Refresh");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(577, 535, -1, -1));

        removeBtn.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        removeBtn.setText("Remove any account???");
        removeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(removeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 164, -1, -1));

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 50, -1, 250));

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, -1));

        jPanel4.setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(1200, 540, 80, 32);

        ClientList.setBackground(new java.awt.Color(102, 0, 255));
        ClientList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account No.", "Name", "Father's Name", "Mother's Name", "Date of Birth", "Marital Status", "Gender", "Email", "Address", "Contact No.", "NID No.", "Amount"
            }
        ));
        ClientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ClientList);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(260, 360, 1920, 100);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banking/management/system/Transactions-7.1 (2).jpg"))); // NOI18N
        jPanel4.add(jLabel2);
        jLabel2.setBounds(260, 0, 2040, 750);

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-260, 0, 2300, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

         

    
    private void FindBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindBtnActionPerformed
        // TODO add your handling code here:
        
        
        LabelMessage.setText("");
        DefaultTableModel model = (DefaultTableModel)ClientList.getModel();
        while(model.getRowCount()>0)
        {
           for(int i=0;i<model.getRowCount();i++){
                   model.removeRow(i);
           }
        }
        
        Statement st=null;
        ResultSet rs=null;
        Connection con;
        String query;
        query = "select * from Account where ID = "+"'"+IDTxt.getText()+"'";
        try {  
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Bank;user=sa;password=sys123";
        

        con = DriverManager.getConnection(connectionUrl);
        
        st=con.createStatement();
        rs=st.executeQuery(query);
        
        int size=0;
        
        while (rs.next())
        {
            size++;
            //System.out.print(rs.getString(1)+" ");
            //System.out.println(rs.getString(2));
            if(rs.getString(1).equals(IDTxt.getText()))
            {
                                
                model.addRow(new Object[]{rs.getString(1),
                rs.getString(2),rs.getString(3),rs.getString(4),
                rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),
                rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)}); 
            }
            else if(!rs.getString(1).equals(IDTxt.getText())) 
            {
                //System.out.println("Unsuccessful");
                LabelMessage.setText("No such client exists in the list");
                
            }
            
           
            
        }
        
        if(size==0)
        {
            //System.out.println("No such user exists");
            LabelMessage.setText("No such client exists in the list");
        }
        
        } catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        } catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
        
        
        //if(rs.getString(2).equals(IDTxt.getText()))
    }//GEN-LAST:event_FindBtnActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void IDTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDTxtMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IDTxtMouseClicked

    private void DatePickerTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatePickerTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DatePickerTxtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       new Admin1().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ClientListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientListMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ClientList.getModel();
        PreAmntTxt.setText(model.getValueAt(ClientList.getSelectedRow(), 11).toString());
    }//GEN-LAST:event_ClientListMouseClicked
//update changing of credit method
    private void CreditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditBtnActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)ClientList.getModel();
        Statement st=null;
        ResultSet rs=null;
        Connection con;
        String query;
        query = "update Account set Amount=Amount+"+NewAmntTxt.getText()+" where ID="+"'"+IDTxt.getText()+"'";
        try {  
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Bank;user=sa;password=sys123";
        
        System.out.println(query);
        con = DriverManager.getConnection(connectionUrl);
        
        st=con.createStatement();
        rs=st.executeQuery(query);
       
        } catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        } catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        } 
    }//GEN-LAST:event_CreditBtnActionPerformed
////update changing of debit method
    private void DebitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DebitBtnActionPerformed
        // TODO add your handling code here:
                DefaultTableModel model = (DefaultTableModel)ClientList.getModel();
        Statement st=null;
        ResultSet rs=null;
        Connection con;
        String query;
        query = "update Account set Amount=Amount-"+NewAmntTxt.getText()+" where ID="+"'"+IDTxt.getText()+"'";
        try {  
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Bank;user=sa;password=sys123";
        
        System.out.println(query);
        con = DriverManager.getConnection(connectionUrl);
        
        st=con.createStatement();
        rs=st.executeQuery(query);
       
        } catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        } catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }//GEN-LAST:event_DebitBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         LabelMessage.setText("");
        DefaultTableModel model = (DefaultTableModel)ClientList.getModel();
        while(model.getRowCount()>0)
        {
           for(int i=0;i<model.getRowCount();i++){
                   model.removeRow(i);
           }
        }
        
        Statement st=null;
        ResultSet rs=null;
        Connection con;
        String query;
        query = "select * from Account where ID = "+"'"+IDTxt.getText()+"'";
        try {  
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Bank;user=sa;password=sys123";
        

        con = DriverManager.getConnection(connectionUrl);
        
        st=con.createStatement();
        rs=st.executeQuery(query);
        
        int size=0;
        
        while (rs.next())
        {
            size++;
            //System.out.print(rs.getString(1)+" ");
            //System.out.println(rs.getString(2));
            if(rs.getString(1).equals(IDTxt.getText()))
            {
                                
                model.addRow(new Object[]{rs.getString(1),
                rs.getString(2),rs.getString(3),rs.getString(4),
                rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),
                rs.getString(9),rs.getString(10),rs.getString(11),rs.getString(12)}); 
            }
            else if(!rs.getString(1).equals(IDTxt.getText())) 
            {
                //System.out.println("Unsuccessful");
                LabelMessage.setText("No such client exists in the list");
                
            }
            
           
            
        }
        
        if(size==0)
        {
            //System.out.println("No such user exists");
            LabelMessage.setText("No such client exists in the list");
        }
        
        } catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        } catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBtnActionPerformed
        // TODO add your handling code here:
         LabelMessage.setText("");
        DefaultTableModel model = (DefaultTableModel)ClientList.getModel();
        while(model.getRowCount()>0)
        {
           for(int i=0;i<model.getRowCount();i++){
                   model.removeRow(i);
           }
        }
        
        Statement st=null;
        ResultSet rs=null;
        Connection con;
        String query;
        query = "delete from Account where ID = "+"'"+IDTxt.getText()+"'";
        try {  
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=Bank;user=sa;password=sys123";
        

        con = DriverManager.getConnection(connectionUrl);
        
        st=con.createStatement();
        rs=st.executeQuery(query);
            System.out.println(query);
      
        
       
        
        } catch (SQLException e) {
            System.out.println("SQL Exception: "+ e.toString());
        } catch (ClassNotFoundException cE) {
            System.out.println("Class Not Found Exception: "+ cE.toString());
        }
    }//GEN-LAST:event_removeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientList;
    private javax.swing.JButton CreditBtn;
    private javax.swing.JButton DebitBtn;
    private javax.swing.JButton FindBtn;
    private javax.swing.JTextField IDTxt;
    private javax.swing.JLabel LabelMessage;
    private javax.swing.JTextField NewAmntTxt;
    private javax.swing.JTextField PreAmntTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
